title: AI那些事
description: 每天三更，带你读懂AI世界的那些事儿
author: miki
url: https://ai.miki.vip
language: zh-CN
timezone: Asia/Shanghai

# 允许发布未来日期的文章
future: true

theme: minima

permalink: /:year/:month/:day/:title.html

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "miki"
